name: 'Webpack'
description: 'Run Webpack action'
inputs:
  directory:
    description: 'Path to the webpack directory'
    required: true
  output-folder:
    description: 'Webpack output path'
    required: true
runs:
  using: "composite"
  steps:
    ### Get latest git commit with changes to the project
    - id: WEBPACK_HASH
      run: echo "hash=$(git log -1 --pretty=format:'%h' --follow '${{ inputs.directory }}')" >> $env:GITHUB_OUTPUT # AXDEVOPS-16: replacement for set-output   
      shell: powershell
    
    ### First make sure the output directory exists, this is needed or cache action will throw an error
    - name: Create Directory.
      run: New-Item -Path "${{ inputs.output-folder }}" -ItemType "directory" -Force
      shell: powershell
        
    ### Check cache action for existing webpack build
    - name: Cache Webpack Build
      id: CACHE_WEBPACK
      uses: actions/cache@v3.3.1
      with:
        path: "${{ inputs.output-folder }}"
        key: webpack-cache-${{steps.WEBPACK_HASH.outputs.hash}}
    
    ### below if will make sure this only runs when webpacks needs to be build 
    - uses: actions/setup-node@v3
      if: steps.CACHE_WEBPACK.outputs.cache-hit != 'true'
      with:
        node-version: '16'
        cache: 'npm'
  
    - name: NPM install
      if: steps.CACHE_WEBPACK.outputs.cache-hit != 'true'
      run: npm install
      working-directory: ${{ inputs.directory }}
      shell: powershell
    - name: Run webpack
      if: steps.CACHE_WEBPACK.outputs.cache-hit != 'true'
      run: npm run build:production
      working-directory: ${{ inputs.directory }}
      shell: powershell